name: Qodana Backend Analysis

on: [push, pull_request]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Qodana
        uses: jetbrains/qodana-action@v1
        with:
          project-dir: ./
          results-dir: qodana-results
          baseline: qodana-baseline.json